#!/usr/bin/env python

Import('env')
Import('env_modules')

env_chipmunk = env_modules.Clone()

# Integration source files
sources = Glob("*.cpp")
sources += Glob("objects/*.cpp")

# Chipmunk source files
sources += [
    "lib/src/chipmunk.c",
    "lib/src/cpArbiter.c",
    "lib/src/cpArray.c",
    "lib/src/cpBBTree.c",
    "lib/src/cpBody.c",
    "lib/src/cpCollision.c",
    "lib/src/cpConstraint.c",
    "lib/src/cpDampedRotarySpring.c",
    "lib/src/cpDampedSpring.c",
    "lib/src/cpGearJoint.c",
    "lib/src/cpGrooveJoint.c",
    "lib/src/cpHashSet.c",
    "lib/src/cpPinJoint.c",
    "lib/src/cpPivotJoint.c",
    "lib/src/cpPolyShape.c",
    "lib/src/cpRatchetJoint.c",
    "lib/src/cpRobust.c",
    "lib/src/cpRotaryLimitJoint.c",
    "lib/src/cpShape.c",
    "lib/src/cpSimpleMotor.c",
    "lib/src/cpSlideJoint.c",
    "lib/src/cpSpace.c",
    "lib/src/cpSpaceComponent.c",
    "lib/src/cpSpaceDebug.c",
    "lib/src/cpSpaceHash.c",
    "lib/src/cpSpaceQuery.c",
    "lib/src/cpSpaceStep.c",
    "lib/src/cpSpatialIndex.c",
    "lib/src/cpSweep1D.c"
]

# Chipmunk include path
env_chipmunk.Append(CPPPATH=["lib/include"])

# Compilation flags
env_chipmunk.Append(CPPFLAGS=["-DCP_USE_DOUBLES=0", "-DCP_SPACE_DISABLE_DEBUG_API"])

# Compile as a static library
lib = env_chipmunk.Library("chipmunk", sources)

# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
